name: pyiron-demonstration
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pyiron_base
  - pyiron_atomistics
  - pyiron_continuum
  - pyiron_experimental
  - damask-mesh
  - damask-grid
  - damask =3.0.0a5
  - fenics =2019.1.0
  - k3d
  - matplotlib
  - mshr =2019.1.0
  - numpy
  - pyiron-data >=0.0.17
  - python-damask
  - pyvista
  - scipy
  - seaborn
  - superlu_dist=6.2.0=*_4
  - scikit-image
  - jupyterlab
